### PR TITLE
Try to improve rust code readability

### PR DESCRIPTION
**Pull request by Lol3rrr**
As suggested in issue #218 

# Type of changes
- Try to flatten code by using early returns/continues if there is only a single happy path in a function or loop
- Change repetitive matches with map_err
- Change matches returning true/false with matches! macro

### CODE REVIEW

**Comment by Lol3rrr** [comment]
I was also thinking about replacing the use of `lazy_static` with the new [LazyLock](https://doc.rust-lang.org/stable/std/sync/struct.LazyLock.html) or similar features in the standard library to remove the dependency, but I was not sure about the supported/used compiler versions

**Comment by LaihoE** [comment]
Looks good! Sure we can replace lazy_static also but maybe make it a separate pr.

**Comment by LaihoE** [comment]
As for the compiler version, It would be good to set the version in the Cargo.toml as protobuf often also has issues with some versions.

**Comment by Lol3rrr** [comment]
I think this is most of the easy to spot things, there are some other parts that seem more complicated and I don't think this would be the right place to change them.

I will open another PR for removing lazy_static and will also see what clippy would suggest

**Comment by LaihoE** [comment]
This contains quite a lot of code already, are you ready to merge this? you can always open a new pr with more refactors.

**Comment by Lol3rrr** [comment]
Yeah I would be ready, in my previous comment I meant that there are potentially more things to do, but they would be in different PRs, sorry if that was not clear.

**Pull request merged**
