### PR TITLE
trigger ci

### PR DESCRIPTION
**Pull request by LaihoE**

### CODE REVIEW

**Comment by LaihoE** [comment]
odd... 3.7 failing but 3.8 is ok.

**Comment by JanEricNitschke** [comment]
Looks like the pandas version that is needed is not compatible with 3.7?

**Comment by LaihoE** [comment]
I'm down to drop 3.7 support its quite ancient... what do you think?

**Comment by JanEricNitschke** [comment]
Its already past EOL: https://devguide.python.org/versions/

So if that is really the issue then i definitely think that it can be dropped.

**Comment by JanEricNitschke** [comment]
If this passes now i think we should also update the pyproject.toml to specify >=3.8 and maybe even the pandas version explicitely that was mentioned in the error message.

**Pull request merged**
