### PR TITLE
Remove old tests

### PR DESCRIPTION
**Pull request by LaihoE**

### CODE REVIEW

**Comment by LaihoE** [comment]
I'll try to fix this later today.

**Comment by JanEricNitschke** [comment]
I think from the current state you just need to move the venv creation above the maturin command.

I couldnt debug this in my PR as it wasnt running there. And it probably also wont actually run here, right? With the way the CI is setup it should always run the broken version in the main branch.

**Comment by LaihoE** [comment]
Shouldn't this: 
ref: ${{ github.event.pull_request.head.sha }}

Fetch the pr branch and not the main branch?

**Comment by LaihoE** [comment]
hmm clearly not fetching the most recent commit :(

**Comment by JanEricNitschke** [comment]
I think it is this: https://github.com/LaihoE/demoparser/blob/remove_old_tests/.github/workflows/ci.yml#L4

That is basically a safety feature that third party PRs cant cause issues with their CI changes.

**Pull request merged**
